services:
  nginx:
    container_name: flow-nginx
    build:
      context: ./
      dockerfile: Dockerfile.nginx
    volumes:
      - ./static:/usr/share/nginx/html
    ports:
      - "80:80"
    environment:
      - NGINX_PORT=80
    profiles: [nginx]
    networks:
      - flow-net

  react:
    container_name: flow-react
    build:
      context: ./
      dockerfile: Dockerfile.react
    volumes:
      - ./static:/output

networks:
  flow-net:
    name: flow-net
